### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kgryte** [math-io/relative-difference#1]
This implementations differs from other [implementations](http://www.boost.org/doc/libs/1_60_0/libs/math/doc/html/math_toolkit/float_comparison.html) in the following ways:
- if `x` and/or `y` is `NaN`, the result is `NaN`. This behavior matches [absolute difference](https://github.com/math-io/absolute-difference). [Boost](http://www.boost.org/doc/libs/1_60_0/libs/math/doc/html/math_toolkit/float_comparison.html), in contrast, returns `max_value` (finite infinity), claiming that `NaNs` imply "infinite" difference.
- if `|x| = |y| = infinity`, the result is `NaN`. This behavior matches [absolute difference](https://github.com/math-io/absolute-difference). Boost, in contrast, returns `0`, claiming that infinities are the same.
- if a scale function returns `0`, the result is `NaN`. Boost, which uses the `min-abs` scale function, prevents DIVIDE-BY-ZERO errors by setting a zero `x` and/or `y` to the minimum normal double. This has the consequence that, e.g., `x = -1e100` and `y = 0`, the relative difference would be `infinity`, which does not seem correct. Part of Boost's rationale is that all subnormals and zero should be effectively considered the same. This implementation bails, returning `NaN`, indicating that the implementation cannot make sense of the results. 
- this implementation does not give special treatment to numbers having a different sign. In [Boost](http://www.boost.org/doc/libs/1_60_0/libs/math/doc/html/math_toolkit/float_comparison.html), if `x` and `y` are different signs, then the relative difference is `max_value`. Why this is the preferred approach in Boost is unknown.

**Comment by kgryte** [comment]
One open question is whether the default `scale` function should be `max-abs` or `min-abs`. Boost uses `min-abs`, which may be due a focus on testing. In `min-abs`, the relative difference is **greater than** `max-abs`. Thus, when used to measure equality, `min-abs` is stricter than when using `max-abs` (i.e., when using `min-abs`, a test is more likely to fail due to a larger relative difference). The `max-abs` approach is, however, a common scale function, where, when it is unknown which of `x` or `y` is the "real" value, sides with the larger (in magnitude) of the two values to assess equality/deviance.

The question is thus whether we want this implementation to take a "weak" or "strong" position on default usage.

**Comment by kgryte** [comment]
The argument for making "strong" the default is the relative difference is conservative in the sense that the result will indicate a larger difference, thus supporting an argument that `x` and `y` are distinct.

The argument for "weak" is that we avoid the following asymmetry. Suppose we wanted to compute the relative difference and determine whether the relative difference is `<= 0.01`. Let `x = 99` and `y = 100`. If we use `x` as the reference, then `(100-99)/99 = 0.01010...`. If we use `y` as the reference, then `(100-99)/100 = 0.01`. In which case, we have a situation in which `99` can be in the "neighborhood" of `100`, but `100` is not the "neighborhood" of `99`. If we always use the **larger** of the two values, both values are either **always** in the same "neighborhood" or **always** distinct. 

Granted, these considerations are floating-point number comparison focused, but would probably be good to be consistent with the forthcoming "approximately equal" module for more formally comparing floating-point numbers.

**Comment by Planeshifter** [comment]
Most choices of yours seem resonable to me. The one I am not so sure about whether it would not be more practical to make the difference between infinity and infinity zero. Now, this is mathematically incorrect, but I imagine using this module to e.g. test functions against a reference implementation, in which case both functions returning infinity does not signal a problem at all. In what use cases would it harm if the result was zero instead of NaN?
The code looks all good to me, by the way.

**Comment by kgryte** [comment]
@Planeshifter This behavior is mainly to be consistent with the absolute difference and the fact that `inf-inf = NaN`. I am willing, however, in a separate module "is-close", which is more testing oriented, to break convention and consider `infinities` the same.

**Comment by Planeshifter** [comment]
Sounds good. Planning to publish this module soon?

**Comment by kgryte** [comment]
Closing and will publish.
